name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
          - Release
        runtime:
          - win10-x64
          - ubuntu.16.10-x64
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - run: dotnet publish --configuration ${{ matrix.configuration }} --output bin --self-contained true --runtime ${{ matrix.runtime }}
    - uses: actions/upload-artifact@v1
      with:
        name: TextClient
        path: bin
